### ISSUE TITLE
suggests ❤️

### ISSUE THREAD

**Issue by Shawkiiz** [bebawy6/bebawy6#1]
First, I would like to thank you for this wonderful file that contains almost all channels

And I would like to suggest some simple things :

- Update "ON E" channel icon for the new one 

- add "Mix" & "Mix blaraby" & "Mix One"

- add "cima" channel

- add "rotana kids" channel

Thx 😊

**Comment by bebawy6** [comment]
Thank you very much for your message. In tomorrow's update, you will see that all of the requested points have been fulfilled.
